export const GET_PRICE_REQUEST = 'GET_PRICE_REQUEST';
export const GET_PRICE_SUCCESS = 'GET_PRICE_SUCCESS';
export const GET_PRICE_FAIL = 'GET_PRICE_FAIL';

export const GET_PRICE_HISTORY_REQUEST = 'GET_PRICE_HISTORY_REQUEST';
export const GET_PRICE_HISTORY_SUCCESS = 'GET_PRICE_HISTORY_SUCCESS';
export const GET_PRICE_HISTORY_FAIL = 'GET_PRICE_HISTORY_FAIL';
