export const GET_STUDENT_REQUEST = 'GET_STUDENT_REQUEST';
export const GET_STUDENT_SUCCESS = 'GET_STUDENT_SUCCESS';
export const GET_STUDENT_FAIL = 'GET_STUDENT_FAIL';

export const POST_STUDENT_REQUEST = 'POST_STUDENT_REQUEST';
export const POST_STUDENT_SUCCESS = 'POST_STUDENT_SUCCESS';
export const POST_STUDENT_FAIL = 'POST_STUDENT_FAIL';

export const PUT_STUDENT_REQUEST = 'PUT_STUDENT_REQUEST';
export const PUT_STUDENT_SUCCESS = 'PUT_STUDENT_SUCCESS';
export const PUT_STUDENT_FAIL = 'PUT_STUDENT_FAIL';

export const DELETE_STUDENT_REQUEST = 'DELETE_STUDENT_REQUEST';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
export const DELETE_STUDENT_FAIL = 'DELETE_STUDENT_FAIL';

export const GET_STUDENT_BY_ID_REQUEST = 'GET_STUDENT_BY_ID_REQUEST';
export const GET_STUDENT_BY_ID_SUCCESS = 'GET_STUDENT_BY_ID_SUCCESS';
export const GET_STUDENT_BY_ID_FAIL = 'GET_STUDENT_BY_ID_FAIL';
